// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        // Firebase has no official Linux SDK. Fall back to web options so
        // Firebase.initializeApp() doesn't crash at compile time; the
        // try/catch in main.dart handles any runtime failure gracefully.
        return web;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCymHKOsfxac45SPAoAqDKjHlotOsIvkP8',
    appId: '1:482473409370:web:7e03c21bf947e69d2a9163',
    messagingSenderId: '482473409370',
    projectId: 'workforce-9b7de',
    authDomain: 'workforce-9b7de.firebaseapp.com',
    storageBucket: 'workforce-9b7de.firebasestorage.app',
    measurementId: 'G-4N3ESQLVRW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCo3vZ6idJqOIdXEegX0NcIZ7M5umAA9T0',
    appId: '1:482473409370:android:d2290c3acab1e7732a9163',
    messagingSenderId: '482473409370',
    projectId: 'workforce-9b7de',
    storageBucket: 'workforce-9b7de.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQJuBUF1cOLN7v0KnMcUZyVT_GBUaTagU',
    appId: '1:482473409370:ios:7d9b61c686b184172a9163',
    messagingSenderId: '482473409370',
    projectId: 'workforce-9b7de',
    storageBucket: 'workforce-9b7de.firebasestorage.app',
    iosBundleId: 'com.devparadise.clearwage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQJuBUF1cOLN7v0KnMcUZyVT_GBUaTagU',
    appId: '1:482473409370:ios:7d9b61c686b184172a9163',
    messagingSenderId: '482473409370',
    projectId: 'workforce-9b7de',
    storageBucket: 'workforce-9b7de.firebasestorage.app',
    iosBundleId: 'com.devparadise.clearwage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCymHKOsfxac45SPAoAqDKjHlotOsIvkP8',
    appId: '1:482473409370:web:18b0dd19da357b152a9163',
    messagingSenderId: '482473409370',
    projectId: 'workforce-9b7de',
    authDomain: 'workforce-9b7de.firebaseapp.com',
    storageBucket: 'workforce-9b7de.firebasestorage.app',
    measurementId: 'G-7L4ZK2DJW4',
  );
}
