// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: crud.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const createDispute = `-- name: CreateDispute :one
INSERT INTO ledger_disputes (tenant_id, ledger_id, employee_id, raised_by, reason)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, ledger_id, employee_id, raised_by, reason, status, resolved_by, resolution_note, created_at, updated_at
`

type CreateDisputeParams struct {
	TenantID   uuid.UUID `json:"tenant_id"`
	LedgerID   uuid.UUID `json:"ledger_id"`
	EmployeeID uuid.UUID `json:"employee_id"`
	RaisedBy   uuid.UUID `json:"raised_by"`
	Reason     string    `json:"reason"`
}

func (q *Queries) CreateDispute(ctx context.Context, arg CreateDisputeParams) (LedgerDispute, error) {
	row := q.db.QueryRowContext(ctx, createDispute,
		arg.TenantID,
		arg.LedgerID,
		arg.EmployeeID,
		arg.RaisedBy,
		arg.Reason,
	)
	var i LedgerDispute
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.LedgerID,
		&i.EmployeeID,
		&i.RaisedBy,
		&i.Reason,
		&i.Status,
		&i.ResolvedBy,
		&i.ResolutionNote,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAttendanceByDateRangeExplicit = `-- name: ListAttendanceByDateRangeExplicit :many
SELECT
  a.id, a.tenant_id, a.employee_id, a.date, a.shift_id,
  a.status, a.check_in_time, a.check_out_time,
  a.overtime_hours, a.overtime_rate_multiplier, a.units_produced,
  a.is_locked, a.edited_by, a.edited_at, a.computed_wage,
  a.created_at, a.updated_at,
  emp.name AS employee_name,
  emp.photo_url AS employee_photo
FROM attendance a
LEFT JOIN employees emp ON a.employee_id = emp.id AND a.tenant_id = emp.tenant_id
WHERE a.tenant_id = $1
  AND a.date >= $2
  AND a.date <= $3
ORDER BY a.date ASC, emp.name ASC
LIMIT $4 OFFSET $5
`

type ListAttendanceByDateRangeExplicitParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Date     time.Time `json:"date"`
	Date_2   time.Time `json:"date_2"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

type ListAttendanceByDateRangeExplicitRow struct {
	ID                     uuid.UUID       `json:"id"`
	TenantID               uuid.UUID       `json:"tenant_id"`
	EmployeeID             uuid.UUID       `json:"employee_id"`
	Date                   time.Time       `json:"date"`
	ShiftID                uuid.NullUUID   `json:"shift_id"`
	Status                 string          `json:"status"`
	CheckInTime            sql.NullTime    `json:"check_in_time"`
	CheckOutTime           sql.NullTime    `json:"check_out_time"`
	OvertimeHours          decimal.Decimal `json:"overtime_hours"`
	OvertimeRateMultiplier decimal.Decimal `json:"overtime_rate_multiplier"`
	UnitsProduced          sql.NullInt32   `json:"units_produced"`
	IsLocked               bool            `json:"is_locked"`
	EditedBy               uuid.NullUUID   `json:"edited_by"`
	EditedAt               sql.NullTime    `json:"edited_at"`
	ComputedWage           sql.NullString  `json:"computed_wage"`
	CreatedAt              time.Time       `json:"created_at"`
	UpdatedAt              time.Time       `json:"updated_at"`
	EmployeeName           sql.NullString  `json:"employee_name"`
	EmployeePhoto          sql.NullString  `json:"employee_photo"`
}

func (q *Queries) ListAttendanceByDateRangeExplicit(ctx context.Context, arg ListAttendanceByDateRangeExplicitParams) ([]ListAttendanceByDateRangeExplicitRow, error) {
	rows, err := q.db.QueryContext(ctx, listAttendanceByDateRangeExplicit,
		arg.TenantID,
		arg.Date,
		arg.Date_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAttendanceByDateRangeExplicitRow{}
	for rows.Next() {
		var i ListAttendanceByDateRangeExplicitRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EmployeeID,
			&i.Date,
			&i.ShiftID,
			&i.Status,
			&i.CheckInTime,
			&i.CheckOutTime,
			&i.OvertimeHours,
			&i.OvertimeRateMultiplier,
			&i.UnitsProduced,
			&i.IsLocked,
			&i.EditedBy,
			&i.EditedAt,
			&i.ComputedWage,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EmployeeName,
			&i.EmployeePhoto,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttendanceByEmployeeMonthExplicit = `-- name: ListAttendanceByEmployeeMonthExplicit :many
SELECT
  a.id, a.tenant_id, a.employee_id, a.date, a.shift_id,
  a.status, a.check_in_time, a.check_out_time,
  a.overtime_hours, a.overtime_rate_multiplier, a.units_produced,
  a.is_locked, a.edited_by, a.edited_at, a.computed_wage,
  a.created_at, a.updated_at,
  emp.name AS employee_name,
  emp.photo_url AS employee_photo
FROM attendance a
LEFT JOIN employees emp ON a.employee_id = emp.id AND a.tenant_id = emp.tenant_id
WHERE a.employee_id = $1
  AND a.tenant_id = $2
  AND a.date >= $3
  AND a.date <= $4
ORDER BY a.date ASC
LIMIT $5 OFFSET $6
`

type ListAttendanceByEmployeeMonthExplicitParams struct {
	EmployeeID uuid.UUID `json:"employee_id"`
	TenantID   uuid.UUID `json:"tenant_id"`
	Date       time.Time `json:"date"`
	Date_2     time.Time `json:"date_2"`
	Limit      int32     `json:"limit"`
	Offset     int32     `json:"offset"`
}

type ListAttendanceByEmployeeMonthExplicitRow struct {
	ID                     uuid.UUID       `json:"id"`
	TenantID               uuid.UUID       `json:"tenant_id"`
	EmployeeID             uuid.UUID       `json:"employee_id"`
	Date                   time.Time       `json:"date"`
	ShiftID                uuid.NullUUID   `json:"shift_id"`
	Status                 string          `json:"status"`
	CheckInTime            sql.NullTime    `json:"check_in_time"`
	CheckOutTime           sql.NullTime    `json:"check_out_time"`
	OvertimeHours          decimal.Decimal `json:"overtime_hours"`
	OvertimeRateMultiplier decimal.Decimal `json:"overtime_rate_multiplier"`
	UnitsProduced          sql.NullInt32   `json:"units_produced"`
	IsLocked               bool            `json:"is_locked"`
	EditedBy               uuid.NullUUID   `json:"edited_by"`
	EditedAt               sql.NullTime    `json:"edited_at"`
	ComputedWage           sql.NullString  `json:"computed_wage"`
	CreatedAt              time.Time       `json:"created_at"`
	UpdatedAt              time.Time       `json:"updated_at"`
	EmployeeName           sql.NullString  `json:"employee_name"`
	EmployeePhoto          sql.NullString  `json:"employee_photo"`
}

func (q *Queries) ListAttendanceByEmployeeMonthExplicit(ctx context.Context, arg ListAttendanceByEmployeeMonthExplicitParams) ([]ListAttendanceByEmployeeMonthExplicitRow, error) {
	rows, err := q.db.QueryContext(ctx, listAttendanceByEmployeeMonthExplicit,
		arg.EmployeeID,
		arg.TenantID,
		arg.Date,
		arg.Date_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAttendanceByEmployeeMonthExplicitRow{}
	for rows.Next() {
		var i ListAttendanceByEmployeeMonthExplicitRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EmployeeID,
			&i.Date,
			&i.ShiftID,
			&i.Status,
			&i.CheckInTime,
			&i.CheckOutTime,
			&i.OvertimeHours,
			&i.OvertimeRateMultiplier,
			&i.UnitsProduced,
			&i.IsLocked,
			&i.EditedBy,
			&i.EditedAt,
			&i.ComputedWage,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EmployeeName,
			&i.EmployeePhoto,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDisputesByTenant = `-- name: ListDisputesByTenant :many
SELECT ld.id, ld.tenant_id, ld.ledger_id, ld.employee_id, ld.raised_by, ld.reason, ld.status, ld.resolved_by, ld.resolution_note, ld.created_at, ld.updated_at, emp.name AS raised_by_name
FROM ledger_disputes ld
LEFT JOIN employees emp ON ld.raised_by = emp.id
WHERE ld.tenant_id = $1 AND ld.status = $2
ORDER BY ld.created_at DESC
LIMIT $3 OFFSET $4
`

type ListDisputesByTenantParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Status   string    `json:"status"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

type ListDisputesByTenantRow struct {
	ID             uuid.UUID      `json:"id"`
	TenantID       uuid.UUID      `json:"tenant_id"`
	LedgerID       uuid.UUID      `json:"ledger_id"`
	EmployeeID     uuid.UUID      `json:"employee_id"`
	RaisedBy       uuid.UUID      `json:"raised_by"`
	Reason         string         `json:"reason"`
	Status         string         `json:"status"`
	ResolvedBy     uuid.NullUUID  `json:"resolved_by"`
	ResolutionNote sql.NullString `json:"resolution_note"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
	RaisedByName   sql.NullString `json:"raised_by_name"`
}

func (q *Queries) ListDisputesByTenant(ctx context.Context, arg ListDisputesByTenantParams) ([]ListDisputesByTenantRow, error) {
	rows, err := q.db.QueryContext(ctx, listDisputesByTenant,
		arg.TenantID,
		arg.Status,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDisputesByTenantRow{}
	for rows.Next() {
		var i ListDisputesByTenantRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.LedgerID,
			&i.EmployeeID,
			&i.RaisedBy,
			&i.Reason,
			&i.Status,
			&i.ResolvedBy,
			&i.ResolutionNote,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RaisedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmployeesByTenantExplicit = `-- name: ListEmployeesByTenantExplicit :many
SELECT
  e.id, e.tenant_id, e.name, e.phone, e.designation,
  e.wage_type, e.wage_amount, e.default_shift_id, e.manager_id,
  e.piece_rate_item_name, e.piece_rate_per_unit, e.daily_target_units,
  e.date_of_joining, e.pan_number, e.aadhaar_number, e.pf_number,
  e.photo_url, e.bank_account_number, e.bank_ifsc, e.upi_id,
  e.emergency_contact_name, e.emergency_contact_phone,
  e.health_notes, e.current_address, e.permanent_address,
  e.role, e.is_active, e.created_at, e.updated_at
FROM employees e
WHERE e.tenant_id = $1
  AND e.is_active = true
ORDER BY e.name ASC
LIMIT $2 OFFSET $3
`

type ListEmployeesByTenantExplicitParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

type ListEmployeesByTenantExplicitRow struct {
	ID                    uuid.UUID       `json:"id"`
	TenantID              uuid.UUID       `json:"tenant_id"`
	Name                  string          `json:"name"`
	Phone                 string          `json:"phone"`
	Designation           sql.NullString  `json:"designation"`
	WageType              string          `json:"wage_type"`
	WageAmount            decimal.Decimal `json:"wage_amount"`
	DefaultShiftID        uuid.NullUUID   `json:"default_shift_id"`
	ManagerID             uuid.NullUUID   `json:"manager_id"`
	PieceRateItemName     sql.NullString  `json:"piece_rate_item_name"`
	PieceRatePerUnit      sql.NullString  `json:"piece_rate_per_unit"`
	DailyTargetUnits      sql.NullInt32   `json:"daily_target_units"`
	DateOfJoining         sql.NullTime    `json:"date_of_joining"`
	PanNumber             sql.NullString  `json:"pan_number"`
	AadhaarNumber         sql.NullString  `json:"aadhaar_number"`
	PfNumber              sql.NullString  `json:"pf_number"`
	PhotoUrl              sql.NullString  `json:"photo_url"`
	BankAccountNumber     sql.NullString  `json:"bank_account_number"`
	BankIfsc              sql.NullString  `json:"bank_ifsc"`
	UpiID                 sql.NullString  `json:"upi_id"`
	EmergencyContactName  sql.NullString  `json:"emergency_contact_name"`
	EmergencyContactPhone sql.NullString  `json:"emergency_contact_phone"`
	HealthNotes           sql.NullString  `json:"health_notes"`
	CurrentAddress        sql.NullString  `json:"current_address"`
	PermanentAddress      sql.NullString  `json:"permanent_address"`
	Role                  string          `json:"role"`
	IsActive              bool            `json:"is_active"`
	CreatedAt             time.Time       `json:"created_at"`
	UpdatedAt             time.Time       `json:"updated_at"`
}

func (q *Queries) ListEmployeesByTenantExplicit(ctx context.Context, arg ListEmployeesByTenantExplicitParams) ([]ListEmployeesByTenantExplicitRow, error) {
	rows, err := q.db.QueryContext(ctx, listEmployeesByTenantExplicit, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEmployeesByTenantExplicitRow{}
	for rows.Next() {
		var i ListEmployeesByTenantExplicitRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Phone,
			&i.Designation,
			&i.WageType,
			&i.WageAmount,
			&i.DefaultShiftID,
			&i.ManagerID,
			&i.PieceRateItemName,
			&i.PieceRatePerUnit,
			&i.DailyTargetUnits,
			&i.DateOfJoining,
			&i.PanNumber,
			&i.AadhaarNumber,
			&i.PfNumber,
			&i.PhotoUrl,
			&i.BankAccountNumber,
			&i.BankIfsc,
			&i.UpiID,
			&i.EmergencyContactName,
			&i.EmergencyContactPhone,
			&i.HealthNotes,
			&i.CurrentAddress,
			&i.PermanentAddress,
			&i.Role,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLedgerByEmployeeMonthExplicit = `-- name: ListLedgerByEmployeeMonthExplicit :many
SELECT
  l.id, l.tenant_id, l.employee_id, l.date, l.type,
  l.amount, l.note, l.linked_payroll_month, l.created_by,
  l.created_at, l.updated_at,
  emp.name AS employee_name,
  emp.photo_url AS employee_photo
FROM ledger l
LEFT JOIN employees emp ON l.employee_id = emp.id AND l.tenant_id = emp.tenant_id
WHERE l.employee_id = $1
  AND l.tenant_id = $2
  AND l.date >= $3
  AND l.date <= $4
ORDER BY l.date ASC
LIMIT $5 OFFSET $6
`

type ListLedgerByEmployeeMonthExplicitParams struct {
	EmployeeID uuid.UUID `json:"employee_id"`
	TenantID   uuid.UUID `json:"tenant_id"`
	Date       time.Time `json:"date"`
	Date_2     time.Time `json:"date_2"`
	Limit      int32     `json:"limit"`
	Offset     int32     `json:"offset"`
}

type ListLedgerByEmployeeMonthExplicitRow struct {
	ID                 uuid.UUID       `json:"id"`
	TenantID           uuid.UUID       `json:"tenant_id"`
	EmployeeID         uuid.UUID       `json:"employee_id"`
	Date               time.Time       `json:"date"`
	Type               string          `json:"type"`
	Amount             decimal.Decimal `json:"amount"`
	Note               sql.NullString  `json:"note"`
	LinkedPayrollMonth sql.NullString  `json:"linked_payroll_month"`
	CreatedBy          uuid.UUID       `json:"created_by"`
	CreatedAt          time.Time       `json:"created_at"`
	UpdatedAt          time.Time       `json:"updated_at"`
	EmployeeName       sql.NullString  `json:"employee_name"`
	EmployeePhoto      sql.NullString  `json:"employee_photo"`
}

func (q *Queries) ListLedgerByEmployeeMonthExplicit(ctx context.Context, arg ListLedgerByEmployeeMonthExplicitParams) ([]ListLedgerByEmployeeMonthExplicitRow, error) {
	rows, err := q.db.QueryContext(ctx, listLedgerByEmployeeMonthExplicit,
		arg.EmployeeID,
		arg.TenantID,
		arg.Date,
		arg.Date_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLedgerByEmployeeMonthExplicitRow{}
	for rows.Next() {
		var i ListLedgerByEmployeeMonthExplicitRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EmployeeID,
			&i.Date,
			&i.Type,
			&i.Amount,
			&i.Note,
			&i.LinkedPayrollMonth,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EmployeeName,
			&i.EmployeePhoto,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLedgerByTenantExplicit = `-- name: ListLedgerByTenantExplicit :many
SELECT
  l.id, l.tenant_id, l.employee_id, l.date, l.type,
  l.amount, l.note, l.linked_payroll_month, l.created_by,
  l.created_at, l.updated_at,
  emp.name AS employee_name,
  emp.photo_url AS employee_photo
FROM ledger l
LEFT JOIN employees emp ON l.employee_id = emp.id AND l.tenant_id = emp.tenant_id
WHERE l.tenant_id = $1
  AND l.date >= $2
  AND l.date <= $3
ORDER BY l.date ASC, emp.name ASC
LIMIT $4 OFFSET $5
`

type ListLedgerByTenantExplicitParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Date     time.Time `json:"date"`
	Date_2   time.Time `json:"date_2"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

type ListLedgerByTenantExplicitRow struct {
	ID                 uuid.UUID       `json:"id"`
	TenantID           uuid.UUID       `json:"tenant_id"`
	EmployeeID         uuid.UUID       `json:"employee_id"`
	Date               time.Time       `json:"date"`
	Type               string          `json:"type"`
	Amount             decimal.Decimal `json:"amount"`
	Note               sql.NullString  `json:"note"`
	LinkedPayrollMonth sql.NullString  `json:"linked_payroll_month"`
	CreatedBy          uuid.UUID       `json:"created_by"`
	CreatedAt          time.Time       `json:"created_at"`
	UpdatedAt          time.Time       `json:"updated_at"`
	EmployeeName       sql.NullString  `json:"employee_name"`
	EmployeePhoto      sql.NullString  `json:"employee_photo"`
}

func (q *Queries) ListLedgerByTenantExplicit(ctx context.Context, arg ListLedgerByTenantExplicitParams) ([]ListLedgerByTenantExplicitRow, error) {
	rows, err := q.db.QueryContext(ctx, listLedgerByTenantExplicit,
		arg.TenantID,
		arg.Date,
		arg.Date_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLedgerByTenantExplicitRow{}
	for rows.Next() {
		var i ListLedgerByTenantExplicitRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EmployeeID,
			&i.Date,
			&i.Type,
			&i.Amount,
			&i.Note,
			&i.LinkedPayrollMonth,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EmployeeName,
			&i.EmployeePhoto,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectDispute = `-- name: RejectDispute :one
UPDATE ledger_disputes
SET status = 'rejected', resolved_by = $2, resolution_note = $3, updated_at = now()
WHERE id = $1 AND tenant_id = $4
RETURNING id, tenant_id, ledger_id, employee_id, raised_by, reason, status, resolved_by, resolution_note, created_at, updated_at
`

type RejectDisputeParams struct {
	ID             uuid.UUID      `json:"id"`
	ResolvedBy     uuid.NullUUID  `json:"resolved_by"`
	ResolutionNote sql.NullString `json:"resolution_note"`
	TenantID       uuid.UUID      `json:"tenant_id"`
}

func (q *Queries) RejectDispute(ctx context.Context, arg RejectDisputeParams) (LedgerDispute, error) {
	row := q.db.QueryRowContext(ctx, rejectDispute,
		arg.ID,
		arg.ResolvedBy,
		arg.ResolutionNote,
		arg.TenantID,
	)
	var i LedgerDispute
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.LedgerID,
		&i.EmployeeID,
		&i.RaisedBy,
		&i.Reason,
		&i.Status,
		&i.ResolvedBy,
		&i.ResolutionNote,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const resolveDispute = `-- name: ResolveDispute :one
UPDATE ledger_disputes
SET status = 'resolved', resolved_by = $2, resolution_note = $3, updated_at = now()
WHERE id = $1 AND tenant_id = $4
RETURNING id, tenant_id, ledger_id, employee_id, raised_by, reason, status, resolved_by, resolution_note, created_at, updated_at
`

type ResolveDisputeParams struct {
	ID             uuid.UUID      `json:"id"`
	ResolvedBy     uuid.NullUUID  `json:"resolved_by"`
	ResolutionNote sql.NullString `json:"resolution_note"`
	TenantID       uuid.UUID      `json:"tenant_id"`
}

func (q *Queries) ResolveDispute(ctx context.Context, arg ResolveDisputeParams) (LedgerDispute, error) {
	row := q.db.QueryRowContext(ctx, resolveDispute,
		arg.ID,
		arg.ResolvedBy,
		arg.ResolutionNote,
		arg.TenantID,
	)
	var i LedgerDispute
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.LedgerID,
		&i.EmployeeID,
		&i.RaisedBy,
		&i.Reason,
		&i.Status,
		&i.ResolvedBy,
		&i.ResolutionNote,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
