// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dashboard.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const getDashboardSnapshot = `-- name: GetDashboardSnapshot :one
SELECT
  (SELECT COUNT(*) FROM employees WHERE employees.tenant_id = $1 AND employees.is_active = true)::int AS total_staff,
  (SELECT COUNT(*) FROM attendance WHERE attendance.tenant_id = $1 AND attendance.date = $2)::int AS attendance_count,
  (SELECT COUNT(*) FROM attendance WHERE attendance.tenant_id = $1 AND attendance.date = $2 AND attendance.status = 'present')::int AS present,
  (SELECT COUNT(*) FROM attendance WHERE attendance.tenant_id = $1 AND attendance.date = $2 AND attendance.status = 'absent')::int AS absent,
  (SELECT COUNT(*) FROM attendance WHERE attendance.tenant_id = $1 AND attendance.date = $2 AND attendance.status IN ('paid_leave','week_off'))::int AS on_leave,
  (SELECT COALESCE(SUM(ledger.amount),0)::numeric FROM ledger WHERE ledger.tenant_id = $1 AND ledger.date = $2 AND ledger.type = 'jama') AS daily_jama_total,
  (SELECT COALESCE(SUM(CASE WHEN ledger.type='jama' THEN ledger.amount ELSE 0 END),0)::numeric
     FROM ledger WHERE ledger.tenant_id = $1 AND ledger.date BETWEEN $3 AND $2) AS wage_bill_mtd,
  (SELECT (COALESCE(SUM(CASE WHEN ledger.type='udhaar' THEN ledger.amount ELSE 0 END),0)
        - COALESCE(SUM(CASE WHEN ledger.type='jama' THEN ledger.amount ELSE 0 END),0))::numeric
     FROM ledger WHERE ledger.tenant_id = $1) AS total_outstanding
`

type GetDashboardSnapshotParams struct {
	TenantID   uuid.UUID `json:"tenant_id"`
	Today      time.Time `json:"today"`
	MonthStart time.Time `json:"month_start"`
}

type GetDashboardSnapshotRow struct {
	TotalStaff       int32           `json:"total_staff"`
	AttendanceCount  int32           `json:"attendance_count"`
	Present          int32           `json:"present"`
	Absent           int32           `json:"absent"`
	OnLeave          int32           `json:"on_leave"`
	DailyJamaTotal   decimal.Decimal `json:"daily_jama_total"`
	WageBillMtd      decimal.Decimal `json:"wage_bill_mtd"`
	TotalOutstanding decimal.Decimal `json:"total_outstanding"`
}

func (q *Queries) GetDashboardSnapshot(ctx context.Context, arg GetDashboardSnapshotParams) (GetDashboardSnapshotRow, error) {
	row := q.db.QueryRowContext(ctx, getDashboardSnapshot, arg.TenantID, arg.Today, arg.MonthStart)
	var i GetDashboardSnapshotRow
	err := row.Scan(
		&i.TotalStaff,
		&i.AttendanceCount,
		&i.Present,
		&i.Absent,
		&i.OnLeave,
		&i.DailyJamaTotal,
		&i.WageBillMtd,
		&i.TotalOutstanding,
	)
	return i, err
}

const listEmployeeBalances = `-- name: ListEmployeeBalances :many
SELECT ledger.employee_id,
  (COALESCE(SUM(CASE WHEN ledger.type = 'jama' THEN ledger.amount ELSE 0 END),0)
    - COALESCE(SUM(CASE WHEN ledger.type = 'udhaar' THEN ledger.amount ELSE 0 END),0))::numeric AS balance
FROM ledger
WHERE ledger.tenant_id = $1
GROUP BY ledger.employee_id
`

type ListEmployeeBalancesRow struct {
	EmployeeID uuid.UUID       `json:"employee_id"`
	Balance    decimal.Decimal `json:"balance"`
}

func (q *Queries) ListEmployeeBalances(ctx context.Context, tenantID uuid.UUID) ([]ListEmployeeBalancesRow, error) {
	rows, err := q.db.QueryContext(ctx, listEmployeeBalances, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEmployeeBalancesRow{}
	for rows.Next() {
		var i ListEmployeeBalancesRow
		if err := rows.Scan(&i.EmployeeID, &i.Balance); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
