// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT COUNT(*)::int AS count
FROM notifications
WHERE tenant_id = $1 AND employee_id = $2 AND is_read = FALSE
`

type CountUnreadNotificationsParams struct {
	TenantID   uuid.UUID `json:"tenant_id"`
	EmployeeID uuid.UUID `json:"employee_id"`
}

func (q *Queries) CountUnreadNotifications(ctx context.Context, arg CountUnreadNotificationsParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, countUnreadNotifications, arg.TenantID, arg.EmployeeID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const createNotification = `-- name: CreateNotification :exec
INSERT INTO notifications (tenant_id, employee_id, type, title, body, entity_type, entity_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateNotificationParams struct {
	TenantID   uuid.UUID      `json:"tenant_id"`
	EmployeeID uuid.UUID      `json:"employee_id"`
	Type       string         `json:"type"`
	Title      string         `json:"title"`
	Body       string         `json:"body"`
	EntityType sql.NullString `json:"entity_type"`
	EntityID   uuid.NullUUID  `json:"entity_id"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) error {
	_, err := q.db.ExecContext(ctx, createNotification,
		arg.TenantID,
		arg.EmployeeID,
		arg.Type,
		arg.Title,
		arg.Body,
		arg.EntityType,
		arg.EntityID,
	)
	return err
}

const deleteFCMTokenByToken = `-- name: DeleteFCMTokenByToken :exec
DELETE FROM fcm_tokens WHERE token = $1
`

func (q *Queries) DeleteFCMTokenByToken(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, deleteFCMTokenByToken, token)
	return err
}

const deleteFCMTokensByEmployee = `-- name: DeleteFCMTokensByEmployee :exec
DELETE FROM fcm_tokens WHERE employee_id = $1 AND tenant_id = $2
`

type DeleteFCMTokensByEmployeeParams struct {
	EmployeeID uuid.UUID `json:"employee_id"`
	TenantID   uuid.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteFCMTokensByEmployee(ctx context.Context, arg DeleteFCMTokensByEmployeeParams) error {
	_, err := q.db.ExecContext(ctx, deleteFCMTokensByEmployee, arg.EmployeeID, arg.TenantID)
	return err
}

const deleteOldNotifications = `-- name: DeleteOldNotifications :exec
DELETE FROM notifications
WHERE created_at < NOW() - INTERVAL '30 days'
`

func (q *Queries) DeleteOldNotifications(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteOldNotifications)
	return err
}

const listAllFCMTokensByTenant = `-- name: ListAllFCMTokensByTenant :many
SELECT id, tenant_id, employee_id, token, platform, created_at, updated_at
FROM fcm_tokens
WHERE tenant_id = $1
`

func (q *Queries) ListAllFCMTokensByTenant(ctx context.Context, tenantID uuid.UUID) ([]FcmToken, error) {
	rows, err := q.db.QueryContext(ctx, listAllFCMTokensByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FcmToken{}
	for rows.Next() {
		var i FcmToken
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EmployeeID,
			&i.Token,
			&i.Platform,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmployeesByTenantForNotify = `-- name: ListEmployeesByTenantForNotify :many
SELECT id FROM employees WHERE tenant_id = $1 AND is_active = TRUE
`

func (q *Queries) ListEmployeesByTenantForNotify(ctx context.Context, tenantID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, listEmployeesByTenantForNotify, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFCMTokensByEmployee = `-- name: ListFCMTokensByEmployee :many
SELECT id, tenant_id, employee_id, token, platform, created_at, updated_at
FROM fcm_tokens
WHERE employee_id = $1
`

func (q *Queries) ListFCMTokensByEmployee(ctx context.Context, employeeID uuid.UUID) ([]FcmToken, error) {
	rows, err := q.db.QueryContext(ctx, listFCMTokensByEmployee, employeeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FcmToken{}
	for rows.Next() {
		var i FcmToken
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EmployeeID,
			&i.Token,
			&i.Platform,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationsByEmployee = `-- name: ListNotificationsByEmployee :many
SELECT id, tenant_id, employee_id, type, title, body, entity_type, entity_id, is_read, created_at
FROM notifications
WHERE tenant_id = $1 AND employee_id = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListNotificationsByEmployeeParams struct {
	TenantID   uuid.UUID `json:"tenant_id"`
	EmployeeID uuid.UUID `json:"employee_id"`
	Limit      int32     `json:"limit"`
	Offset     int32     `json:"offset"`
}

func (q *Queries) ListNotificationsByEmployee(ctx context.Context, arg ListNotificationsByEmployeeParams) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, listNotificationsByEmployee,
		arg.TenantID,
		arg.EmployeeID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EmployeeID,
			&i.Type,
			&i.Title,
			&i.Body,
			&i.EntityType,
			&i.EntityID,
			&i.IsRead,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSupervisorsByTenant = `-- name: ListSupervisorsByTenant :many
SELECT id FROM employees WHERE tenant_id = $1 AND role IN ('owner', 'supervisor') AND is_active = TRUE
`

func (q *Queries) ListSupervisorsByTenant(ctx context.Context, tenantID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, listSupervisorsByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :exec
UPDATE notifications SET is_read = TRUE
WHERE tenant_id = $1 AND employee_id = $2 AND is_read = FALSE
`

type MarkAllNotificationsReadParams struct {
	TenantID   uuid.UUID `json:"tenant_id"`
	EmployeeID uuid.UUID `json:"employee_id"`
}

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, arg MarkAllNotificationsReadParams) error {
	_, err := q.db.ExecContext(ctx, markAllNotificationsRead, arg.TenantID, arg.EmployeeID)
	return err
}

const markNotificationRead = `-- name: MarkNotificationRead :exec
UPDATE notifications SET is_read = TRUE
WHERE id = $1 AND tenant_id = $2 AND employee_id = $3
`

type MarkNotificationReadParams struct {
	ID         uuid.UUID `json:"id"`
	TenantID   uuid.UUID `json:"tenant_id"`
	EmployeeID uuid.UUID `json:"employee_id"`
}

func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) error {
	_, err := q.db.ExecContext(ctx, markNotificationRead, arg.ID, arg.TenantID, arg.EmployeeID)
	return err
}

const upsertFCMToken = `-- name: UpsertFCMToken :exec
INSERT INTO fcm_tokens (tenant_id, employee_id, token, platform, updated_at)
VALUES ($1, $2, $3, $4, NOW())
ON CONFLICT (token) DO UPDATE
SET employee_id = EXCLUDED.employee_id,
    tenant_id = EXCLUDED.tenant_id,
    platform = EXCLUDED.platform,
    updated_at = NOW()
`

type UpsertFCMTokenParams struct {
	TenantID   uuid.UUID `json:"tenant_id"`
	EmployeeID uuid.UUID `json:"employee_id"`
	Token      string    `json:"token"`
	Platform   string    `json:"platform"`
}

func (q *Queries) UpsertFCMToken(ctx context.Context, arg UpsertFCMTokenParams) error {
	_, err := q.db.ExecContext(ctx, upsertFCMToken,
		arg.TenantID,
		arg.EmployeeID,
		arg.Token,
		arg.Platform,
	)
	return err
}
