// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateDispute(ctx context.Context, arg CreateDisputeParams) (LedgerDispute, error)
	GetDailySummary(ctx context.Context, arg GetDailySummaryParams) (GetDailySummaryRow, error)
	GetDashboardSnapshot(ctx context.Context, arg GetDashboardSnapshotParams) (GetDashboardSnapshotRow, error)
	GetWageBillTrends(ctx context.Context, arg GetWageBillTrendsParams) ([]GetWageBillTrendsRow, error)
	ListAttendanceByDateRangeExplicit(ctx context.Context, arg ListAttendanceByDateRangeExplicitParams) ([]ListAttendanceByDateRangeExplicitRow, error)
	ListAttendanceByEmployeeMonthExplicit(ctx context.Context, arg ListAttendanceByEmployeeMonthExplicitParams) ([]ListAttendanceByEmployeeMonthExplicitRow, error)
	ListDisputesByTenant(ctx context.Context, arg ListDisputesByTenantParams) ([]ListDisputesByTenantRow, error)
	ListEmployeeBalances(ctx context.Context, tenantID uuid.UUID) ([]ListEmployeeBalancesRow, error)
	ListEmployeesByTenantExplicit(ctx context.Context, arg ListEmployeesByTenantExplicitParams) ([]ListEmployeesByTenantExplicitRow, error)
	ListLedgerByEmployeeMonthExplicit(ctx context.Context, arg ListLedgerByEmployeeMonthExplicitParams) ([]ListLedgerByEmployeeMonthExplicitRow, error)
	ListLedgerByTenantExplicit(ctx context.Context, arg ListLedgerByTenantExplicitParams) ([]ListLedgerByTenantExplicitRow, error)
	ListRosterByDate(ctx context.Context, arg ListRosterByDateParams) ([]ListRosterByDateRow, error)
	RejectDispute(ctx context.Context, arg RejectDisputeParams) (LedgerDispute, error)
	ResolveDispute(ctx context.Context, arg ResolveDisputeParams) (LedgerDispute, error)
}

var _ Querier = (*Queries)(nil)
