// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reports.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getDailySummary = `-- name: GetDailySummary :one
SELECT
  (SELECT COUNT(*) FROM employees WHERE employees.tenant_id = $1 AND employees.is_active = true)::int AS total_workers,
  (SELECT COUNT(*) FROM attendance WHERE attendance.tenant_id = $1 AND attendance.date = $2 AND attendance.status = 'present')::int AS present,
  (SELECT COUNT(*) FROM attendance WHERE attendance.tenant_id = $1 AND attendance.date = $2 AND attendance.status = 'absent')::int AS absent,
  (SELECT COUNT(*) FROM attendance WHERE attendance.tenant_id = $1 AND attendance.date = $2 AND attendance.status IN ('paid_leave','week_off'))::int AS on_leave,
  (SELECT COALESCE(SUM(
    CASE WHEN emp.wage_type = 'monthly' THEN emp.wage_amount / 30.0
         ELSE emp.wage_amount
    END), 0)::float8
   FROM attendance a
   JOIN employees emp ON a.employee_id = emp.id AND a.tenant_id = emp.tenant_id
   WHERE a.tenant_id = $1 AND a.date = $2 AND a.status = 'present') AS total_wage_bill
`

type GetDailySummaryParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Date     time.Time `json:"date"`
}

type GetDailySummaryRow struct {
	TotalWorkers  int32   `json:"total_workers"`
	Present       int32   `json:"present"`
	Absent        int32   `json:"absent"`
	OnLeave       int32   `json:"on_leave"`
	TotalWageBill float64 `json:"total_wage_bill"`
}

func (q *Queries) GetDailySummary(ctx context.Context, arg GetDailySummaryParams) (GetDailySummaryRow, error) {
	row := q.db.QueryRowContext(ctx, getDailySummary, arg.TenantID, arg.Date)
	var i GetDailySummaryRow
	err := row.Scan(
		&i.TotalWorkers,
		&i.Present,
		&i.Absent,
		&i.OnLeave,
		&i.TotalWageBill,
	)
	return i, err
}

const getWageBillTrends = `-- name: GetWageBillTrends :many
WITH monthly_attendance AS (
  SELECT
    date_trunc('month', a.date) AS month,
    a.employee_id,
    COUNT(*) AS days_present
  FROM attendance a
  WHERE a.tenant_id = $1
    AND a.date >= $2
    AND a.date < $3
    AND a.status = 'present'
  GROUP BY date_trunc('month', a.date), a.employee_id
)
SELECT
  to_char(ma.month, 'YYYY-MM') AS month,
  COALESCE(SUM(CASE
    WHEN e.wage_type = 'monthly' THEN e.wage_amount
    ELSE e.wage_amount * ma.days_present
  END), 0)::float8 AS total_wages,
  COUNT(DISTINCT ma.employee_id)::int AS headcount
FROM monthly_attendance ma
JOIN employees e ON ma.employee_id = e.id AND e.tenant_id = $1
GROUP BY ma.month
ORDER BY ma.month DESC
`

type GetWageBillTrendsParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Date     time.Time `json:"date"`
	Date_2   time.Time `json:"date_2"`
}

type GetWageBillTrendsRow struct {
	Month      string  `json:"month"`
	TotalWages float64 `json:"total_wages"`
	Headcount  int32   `json:"headcount"`
}

func (q *Queries) GetWageBillTrends(ctx context.Context, arg GetWageBillTrendsParams) ([]GetWageBillTrendsRow, error) {
	rows, err := q.db.QueryContext(ctx, getWageBillTrends, arg.TenantID, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetWageBillTrendsRow{}
	for rows.Next() {
		var i GetWageBillTrendsRow
		if err := rows.Scan(&i.Month, &i.TotalWages, &i.Headcount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
