// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: roster.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const listRosterByDate = `-- name: ListRosterByDate :many
SELECT
  e.id                                        AS employee_id,
  e.name,
  e.phone,
  e.photo_url,
  e.designation,
  e.role,
  e.is_active,
  e.default_shift_id,
  a.shift_id                                  AS attendance_shift_id,
  COALESCE(a.shift_id, e.default_shift_id)    AS shift_id,
  COALESCE(att_s.name, def_s.name)            AS shift_name,
  COALESCE(att_s.start_time, def_s.start_time)::text AS shift_start_time,
  COALESCE(att_s.end_time, def_s.end_time)::text     AS shift_end_time,
  a.id                                        AS attendance_id,
  a.status,
  a.check_in_time,
  a.check_out_time,
  a.overtime_hours,
  a.is_locked,
  a.computed_wage,
  a.version
FROM employees e
LEFT JOIN shifts def_s
  ON e.default_shift_id = def_s.id
  AND def_s.tenant_id = e.tenant_id
LEFT JOIN attendance a
  ON a.employee_id = e.id
  AND a.tenant_id = e.tenant_id
  AND a.date = $1
LEFT JOIN shifts att_s
  ON a.shift_id = att_s.id
  AND att_s.tenant_id = a.tenant_id
WHERE e.tenant_id = $2
  AND e.is_active = true
ORDER BY e.name ASC
`

type ListRosterByDateParams struct {
	Date     time.Time `json:"date"`
	TenantID uuid.UUID `json:"tenant_id"`
}

type ListRosterByDateRow struct {
	EmployeeID        uuid.UUID      `json:"employee_id"`
	Name              string         `json:"name"`
	Phone             string         `json:"phone"`
	PhotoUrl          sql.NullString `json:"photo_url"`
	Designation       sql.NullString `json:"designation"`
	Role              string         `json:"role"`
	IsActive          bool           `json:"is_active"`
	DefaultShiftID    uuid.NullUUID  `json:"default_shift_id"`
	AttendanceShiftID uuid.NullUUID  `json:"attendance_shift_id"`
	ShiftID           uuid.NullUUID  `json:"shift_id"`
	ShiftName         string         `json:"shift_name"`
	ShiftStartTime    string         `json:"shift_start_time"`
	ShiftEndTime      string         `json:"shift_end_time"`
	AttendanceID      uuid.NullUUID  `json:"attendance_id"`
	Status            sql.NullString `json:"status"`
	CheckInTime       sql.NullTime   `json:"check_in_time"`
	CheckOutTime      sql.NullTime   `json:"check_out_time"`
	OvertimeHours     sql.NullString `json:"overtime_hours"`
	IsLocked          sql.NullBool   `json:"is_locked"`
	ComputedWage      sql.NullString `json:"computed_wage"`
	Version           sql.NullInt32  `json:"version"`
}

func (q *Queries) ListRosterByDate(ctx context.Context, arg ListRosterByDateParams) ([]ListRosterByDateRow, error) {
	rows, err := q.db.QueryContext(ctx, listRosterByDate, arg.Date, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRosterByDateRow{}
	for rows.Next() {
		var i ListRosterByDateRow
		if err := rows.Scan(
			&i.EmployeeID,
			&i.Name,
			&i.Phone,
			&i.PhotoUrl,
			&i.Designation,
			&i.Role,
			&i.IsActive,
			&i.DefaultShiftID,
			&i.AttendanceShiftID,
			&i.ShiftID,
			&i.ShiftName,
			&i.ShiftStartTime,
			&i.ShiftEndTime,
			&i.AttendanceID,
			&i.Status,
			&i.CheckInTime,
			&i.CheckOutTime,
			&i.OvertimeHours,
			&i.IsLocked,
			&i.ComputedWage,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
