version: "2"

linters-settings:
  errcheck:
    check-blank: true
  misspell:
    locale: US
  govet:
    enable:
      - shadow

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - misspell

run:
  timeout: 5m
  tests: true
