// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vivek-app/vivek_app/repositories (interfaces: Querier)
//
// Generated by this command:
//
//	mockgen -package mocks -destination mocks/querier.go github.com/vivek-app/vivek_app/repositories Querier
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	repositories "github.com/vivek-app/vivek_app/repositories"
	gomock "go.uber.org/mock/gomock"
)

// MockQuerier is a mock of Querier interface.
type MockQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockQuerierMockRecorder
	isgomock struct{}
}

// MockQuerierMockRecorder is the mock recorder for MockQuerier.
type MockQuerierMockRecorder struct {
	mock *MockQuerier
}

// NewMockQuerier creates a new mock instance.
func NewMockQuerier(ctrl *gomock.Controller) *MockQuerier {
	mock := &MockQuerier{ctrl: ctrl}
	mock.recorder = &MockQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuerier) EXPECT() *MockQuerierMockRecorder {
	return m.recorder
}

// BulkUpsertAttendance mocks base method.
func (m *MockQuerier) BulkUpsertAttendance(ctx context.Context, arg repositories.BulkUpsertAttendanceParams) ([]repositories.Attendance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkUpsertAttendance", ctx, arg)
	ret0, _ := ret[0].([]repositories.Attendance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BulkUpsertAttendance indicates an expected call of BulkUpsertAttendance.
func (mr *MockQuerierMockRecorder) BulkUpsertAttendance(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkUpsertAttendance", reflect.TypeOf((*MockQuerier)(nil).BulkUpsertAttendance), ctx, arg)
}

// CreateActivityLog mocks base method.
func (m *MockQuerier) CreateActivityLog(ctx context.Context, arg repositories.CreateActivityLogParams) (repositories.ActivityLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateActivityLog", ctx, arg)
	ret0, _ := ret[0].(repositories.ActivityLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateActivityLog indicates an expected call of CreateActivityLog.
func (mr *MockQuerierMockRecorder) CreateActivityLog(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateActivityLog", reflect.TypeOf((*MockQuerier)(nil).CreateActivityLog), ctx, arg)
}

// CreateAdvanceRequest mocks base method.
func (m *MockQuerier) CreateAdvanceRequest(ctx context.Context, arg repositories.CreateAdvanceRequestParams) (repositories.AdvanceRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAdvanceRequest", ctx, arg)
	ret0, _ := ret[0].(repositories.AdvanceRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAdvanceRequest indicates an expected call of CreateAdvanceRequest.
func (mr *MockQuerierMockRecorder) CreateAdvanceRequest(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAdvanceRequest", reflect.TypeOf((*MockQuerier)(nil).CreateAdvanceRequest), ctx, arg)
}

// CreateAttendance mocks base method.
func (m *MockQuerier) CreateAttendance(ctx context.Context, arg repositories.CreateAttendanceParams) (repositories.Attendance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAttendance", ctx, arg)
	ret0, _ := ret[0].(repositories.Attendance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAttendance indicates an expected call of CreateAttendance.
func (mr *MockQuerierMockRecorder) CreateAttendance(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAttendance", reflect.TypeOf((*MockQuerier)(nil).CreateAttendance), ctx, arg)
}

// CreateEmployee mocks base method.
func (m *MockQuerier) CreateEmployee(ctx context.Context, arg repositories.CreateEmployeeParams) (repositories.Employee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEmployee", ctx, arg)
	ret0, _ := ret[0].(repositories.Employee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateEmployee indicates an expected call of CreateEmployee.
func (mr *MockQuerierMockRecorder) CreateEmployee(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEmployee", reflect.TypeOf((*MockQuerier)(nil).CreateEmployee), ctx, arg)
}

// CreateHoliday mocks base method.
func (m *MockQuerier) CreateHoliday(ctx context.Context, arg repositories.CreateHolidayParams) (repositories.Holiday, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateHoliday", ctx, arg)
	ret0, _ := ret[0].(repositories.Holiday)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateHoliday indicates an expected call of CreateHoliday.
func (mr *MockQuerierMockRecorder) CreateHoliday(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateHoliday", reflect.TypeOf((*MockQuerier)(nil).CreateHoliday), ctx, arg)
}

// CreateLedgerEntry mocks base method.
func (m *MockQuerier) CreateLedgerEntry(ctx context.Context, arg repositories.CreateLedgerEntryParams) (repositories.Ledger, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLedgerEntry", ctx, arg)
	ret0, _ := ret[0].(repositories.Ledger)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateLedgerEntry indicates an expected call of CreateLedgerEntry.
func (mr *MockQuerierMockRecorder) CreateLedgerEntry(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLedgerEntry", reflect.TypeOf((*MockQuerier)(nil).CreateLedgerEntry), ctx, arg)
}

// CreateShift mocks base method.
func (m *MockQuerier) CreateShift(ctx context.Context, arg repositories.CreateShiftParams) (repositories.Shift, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateShift", ctx, arg)
	ret0, _ := ret[0].(repositories.Shift)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateShift indicates an expected call of CreateShift.
func (mr *MockQuerierMockRecorder) CreateShift(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateShift", reflect.TypeOf((*MockQuerier)(nil).CreateShift), ctx, arg)
}

// CreateSyncEvent mocks base method.
func (m *MockQuerier) CreateSyncEvent(ctx context.Context, arg repositories.CreateSyncEventParams) (repositories.SyncQueue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSyncEvent", ctx, arg)
	ret0, _ := ret[0].(repositories.SyncQueue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSyncEvent indicates an expected call of CreateSyncEvent.
func (mr *MockQuerierMockRecorder) CreateSyncEvent(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSyncEvent", reflect.TypeOf((*MockQuerier)(nil).CreateSyncEvent), ctx, arg)
}

// CreateTenant mocks base method.
func (m *MockQuerier) CreateTenant(ctx context.Context, arg repositories.CreateTenantParams) (repositories.Tenant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTenant", ctx, arg)
	ret0, _ := ret[0].(repositories.Tenant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTenant indicates an expected call of CreateTenant.
func (mr *MockQuerierMockRecorder) CreateTenant(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTenant", reflect.TypeOf((*MockQuerier)(nil).CreateTenant), ctx, arg)
}

// DeleteHoliday mocks base method.
func (m *MockQuerier) DeleteHoliday(ctx context.Context, arg repositories.DeleteHolidayParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteHoliday", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteHoliday indicates an expected call of DeleteHoliday.
func (mr *MockQuerierMockRecorder) DeleteHoliday(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteHoliday", reflect.TypeOf((*MockQuerier)(nil).DeleteHoliday), ctx, arg)
}

// DeleteShift mocks base method.
func (m *MockQuerier) DeleteShift(ctx context.Context, arg repositories.DeleteShiftParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteShift", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteShift indicates an expected call of DeleteShift.
func (mr *MockQuerierMockRecorder) DeleteShift(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteShift", reflect.TypeOf((*MockQuerier)(nil).DeleteShift), ctx, arg)
}

// DeleteTenant mocks base method.
func (m *MockQuerier) DeleteTenant(ctx context.Context, tenantID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTenant", ctx, tenantID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTenant indicates an expected call of DeleteTenant.
func (mr *MockQuerierMockRecorder) DeleteTenant(ctx, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTenant", reflect.TypeOf((*MockQuerier)(nil).DeleteTenant), ctx, tenantID)
}

// FindEmployeeByID mocks base method.
func (m *MockQuerier) FindEmployeeByID(ctx context.Context, arg repositories.FindEmployeeByIDParams) (repositories.Employee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindEmployeeByID", ctx, arg)
	ret0, _ := ret[0].(repositories.Employee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindEmployeeByID indicates an expected call of FindEmployeeByID.
func (mr *MockQuerierMockRecorder) FindEmployeeByID(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindEmployeeByID", reflect.TypeOf((*MockQuerier)(nil).FindEmployeeByID), ctx, arg)
}

// FindEmployeeByPhone mocks base method.
func (m *MockQuerier) FindEmployeeByPhone(ctx context.Context, arg repositories.FindEmployeeByPhoneParams) (repositories.Employee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindEmployeeByPhone", ctx, arg)
	ret0, _ := ret[0].(repositories.Employee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindEmployeeByPhone indicates an expected call of FindEmployeeByPhone.
func (mr *MockQuerierMockRecorder) FindEmployeeByPhone(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindEmployeeByPhone", reflect.TypeOf((*MockQuerier)(nil).FindEmployeeByPhone), ctx, arg)
}

// FindEmployeeByPhoneOnly mocks base method.
func (m *MockQuerier) FindEmployeeByPhoneOnly(ctx context.Context, phone string) (repositories.Employee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindEmployeeByPhoneOnly", ctx, phone)
	ret0, _ := ret[0].(repositories.Employee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindEmployeeByPhoneOnly indicates an expected call of FindEmployeeByPhoneOnly.
func (mr *MockQuerierMockRecorder) FindEmployeeByPhoneOnly(ctx, phone any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindEmployeeByPhoneOnly", reflect.TypeOf((*MockQuerier)(nil).FindEmployeeByPhoneOnly), ctx, phone)
}

// FindShiftByID mocks base method.
func (m *MockQuerier) FindShiftByID(ctx context.Context, arg repositories.FindShiftByIDParams) (repositories.Shift, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindShiftByID", ctx, arg)
	ret0, _ := ret[0].(repositories.Shift)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindShiftByID indicates an expected call of FindShiftByID.
func (mr *MockQuerierMockRecorder) FindShiftByID(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindShiftByID", reflect.TypeOf((*MockQuerier)(nil).FindShiftByID), ctx, arg)
}

// FindSyncEventByEventID mocks base method.
func (m *MockQuerier) FindSyncEventByEventID(ctx context.Context, arg repositories.FindSyncEventByEventIDParams) (repositories.SyncQueue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindSyncEventByEventID", ctx, arg)
	ret0, _ := ret[0].(repositories.SyncQueue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindSyncEventByEventID indicates an expected call of FindSyncEventByEventID.
func (mr *MockQuerierMockRecorder) FindSyncEventByEventID(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindSyncEventByEventID", reflect.TypeOf((*MockQuerier)(nil).FindSyncEventByEventID), ctx, arg)
}

// FindTenantByID mocks base method.
func (m *MockQuerier) FindTenantByID(ctx context.Context, id string) (repositories.Tenant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindTenantByID", ctx, id)
	ret0, _ := ret[0].(repositories.Tenant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindTenantByID indicates an expected call of FindTenantByID.
func (mr *MockQuerierMockRecorder) FindTenantByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindTenantByID", reflect.TypeOf((*MockQuerier)(nil).FindTenantByID), ctx, id)
}

// FindTenantByPhone mocks base method.
func (m *MockQuerier) FindTenantByPhone(ctx context.Context, phone string) (repositories.Tenant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindTenantByPhone", ctx, phone)
	ret0, _ := ret[0].(repositories.Tenant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindTenantByPhone indicates an expected call of FindTenantByPhone.
func (mr *MockQuerierMockRecorder) FindTenantByPhone(ctx, phone any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindTenantByPhone", reflect.TypeOf((*MockQuerier)(nil).FindTenantByPhone), ctx, phone)
}

// GetBalanceByEmployee mocks base method.
func (m *MockQuerier) GetBalanceByEmployee(ctx context.Context, arg repositories.GetBalanceByEmployeeParams) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalanceByEmployee", ctx, arg)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalanceByEmployee indicates an expected call of GetBalanceByEmployee.
func (mr *MockQuerierMockRecorder) GetBalanceByEmployee(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalanceByEmployee", reflect.TypeOf((*MockQuerier)(nil).GetBalanceByEmployee), ctx, arg)
}

// GetDailyJamaTotal mocks base method.
func (m *MockQuerier) GetDailyJamaTotal(ctx context.Context, tenantID, date string) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDailyJamaTotal", ctx, tenantID, date)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDailyJamaTotal indicates an expected call of GetDailyJamaTotal.
func (mr *MockQuerierMockRecorder) GetDailyJamaTotal(ctx, tenantID, date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDailyJamaTotal", reflect.TypeOf((*MockQuerier)(nil).GetDailyJamaTotal), ctx, tenantID, date)
}

// GetLeavePolicyByTenant mocks base method.
func (m *MockQuerier) GetLeavePolicyByTenant(ctx context.Context, tenantID string) (repositories.LeavePolicy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLeavePolicyByTenant", ctx, tenantID)
	ret0, _ := ret[0].(repositories.LeavePolicy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLeavePolicyByTenant indicates an expected call of GetLeavePolicyByTenant.
func (mr *MockQuerierMockRecorder) GetLeavePolicyByTenant(ctx, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLeavePolicyByTenant", reflect.TypeOf((*MockQuerier)(nil).GetLeavePolicyByTenant), ctx, tenantID)
}

// GetStaffProfile mocks base method.
func (m *MockQuerier) GetStaffProfile(ctx context.Context, arg repositories.GetStaffProfileParams) (repositories.StaffProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStaffProfile", ctx, arg)
	ret0, _ := ret[0].(repositories.StaffProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStaffProfile indicates an expected call of GetStaffProfile.
func (mr *MockQuerierMockRecorder) GetStaffProfile(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStaffProfile", reflect.TypeOf((*MockQuerier)(nil).GetStaffProfile), ctx, arg)
}

// GetTenantConfig mocks base method.
func (m *MockQuerier) GetTenantConfig(ctx context.Context, tenantID string) (repositories.TenantConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTenantConfig", ctx, tenantID)
	ret0, _ := ret[0].(repositories.TenantConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTenantConfig indicates an expected call of GetTenantConfig.
func (mr *MockQuerierMockRecorder) GetTenantConfig(ctx, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTenantConfig", reflect.TypeOf((*MockQuerier)(nil).GetTenantConfig), ctx, tenantID)
}

// GetTotalOutstanding mocks base method.
func (m *MockQuerier) GetTotalOutstanding(ctx context.Context, tenantID string) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTotalOutstanding", ctx, tenantID)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTotalOutstanding indicates an expected call of GetTotalOutstanding.
func (mr *MockQuerierMockRecorder) GetTotalOutstanding(ctx, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTotalOutstanding", reflect.TypeOf((*MockQuerier)(nil).GetTotalOutstanding), ctx, tenantID)
}

// ListActivityLogsByTenant mocks base method.
func (m *MockQuerier) ListActivityLogsByTenant(ctx context.Context, arg repositories.ListActivityLogsByTenantParams) ([]repositories.ActivityLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListActivityLogsByTenant", ctx, arg)
	ret0, _ := ret[0].([]repositories.ActivityLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListActivityLogsByTenant indicates an expected call of ListActivityLogsByTenant.
func (mr *MockQuerierMockRecorder) ListActivityLogsByTenant(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListActivityLogsByTenant", reflect.TypeOf((*MockQuerier)(nil).ListActivityLogsByTenant), ctx, arg)
}

// ListAdvanceRequestsByTenant mocks base method.
func (m *MockQuerier) ListAdvanceRequestsByTenant(ctx context.Context, arg repositories.ListAdvanceRequestsByTenantParams) ([]repositories.AdvanceRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAdvanceRequestsByTenant", ctx, arg)
	ret0, _ := ret[0].([]repositories.AdvanceRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAdvanceRequestsByTenant indicates an expected call of ListAdvanceRequestsByTenant.
func (mr *MockQuerierMockRecorder) ListAdvanceRequestsByTenant(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAdvanceRequestsByTenant", reflect.TypeOf((*MockQuerier)(nil).ListAdvanceRequestsByTenant), ctx, arg)
}

// ListAttendanceByDate mocks base method.
func (m *MockQuerier) ListAttendanceByDate(ctx context.Context, arg repositories.ListAttendanceByDateParams) ([]repositories.Attendance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAttendanceByDate", ctx, arg)
	ret0, _ := ret[0].([]repositories.Attendance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAttendanceByDate indicates an expected call of ListAttendanceByDate.
func (mr *MockQuerierMockRecorder) ListAttendanceByDate(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAttendanceByDate", reflect.TypeOf((*MockQuerier)(nil).ListAttendanceByDate), ctx, arg)
}

// ListAttendanceByDateRange mocks base method.
func (m *MockQuerier) ListAttendanceByDateRange(ctx context.Context, arg repositories.ListAttendanceByDateRangeParams) ([]repositories.Attendance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAttendanceByDateRange", ctx, arg)
	ret0, _ := ret[0].([]repositories.Attendance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAttendanceByDateRange indicates an expected call of ListAttendanceByDateRange.
func (mr *MockQuerierMockRecorder) ListAttendanceByDateRange(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAttendanceByDateRange", reflect.TypeOf((*MockQuerier)(nil).ListAttendanceByDateRange), ctx, arg)
}

// ListAttendanceByEmployeeMonth mocks base method.
func (m *MockQuerier) ListAttendanceByEmployeeMonth(ctx context.Context, arg repositories.ListAttendanceByEmployeeMonthParams) ([]repositories.Attendance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAttendanceByEmployeeMonth", ctx, arg)
	ret0, _ := ret[0].([]repositories.Attendance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAttendanceByEmployeeMonth indicates an expected call of ListAttendanceByEmployeeMonth.
func (mr *MockQuerierMockRecorder) ListAttendanceByEmployeeMonth(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAttendanceByEmployeeMonth", reflect.TypeOf((*MockQuerier)(nil).ListAttendanceByEmployeeMonth), ctx, arg)
}

// ListEmployeesByTenant mocks base method.
func (m *MockQuerier) ListEmployeesByTenant(ctx context.Context, arg repositories.ListEmployeesByTenantParams) ([]repositories.Employee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEmployeesByTenant", ctx, arg)
	ret0, _ := ret[0].([]repositories.Employee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEmployeesByTenant indicates an expected call of ListEmployeesByTenant.
func (mr *MockQuerierMockRecorder) ListEmployeesByTenant(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEmployeesByTenant", reflect.TypeOf((*MockQuerier)(nil).ListEmployeesByTenant), ctx, arg)
}

// ListHolidaysByTenant mocks base method.
func (m *MockQuerier) ListHolidaysByTenant(ctx context.Context, arg repositories.ListHolidaysByTenantParams) ([]repositories.Holiday, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListHolidaysByTenant", ctx, arg)
	ret0, _ := ret[0].([]repositories.Holiday)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListHolidaysByTenant indicates an expected call of ListHolidaysByTenant.
func (mr *MockQuerierMockRecorder) ListHolidaysByTenant(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListHolidaysByTenant", reflect.TypeOf((*MockQuerier)(nil).ListHolidaysByTenant), ctx, arg)
}

// ListLedgerByEmployeeMonth mocks base method.
func (m *MockQuerier) ListLedgerByEmployeeMonth(ctx context.Context, arg repositories.ListLedgerByEmployeeMonthParams) ([]repositories.Ledger, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLedgerByEmployeeMonth", ctx, arg)
	ret0, _ := ret[0].([]repositories.Ledger)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListLedgerByEmployeeMonth indicates an expected call of ListLedgerByEmployeeMonth.
func (mr *MockQuerierMockRecorder) ListLedgerByEmployeeMonth(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLedgerByEmployeeMonth", reflect.TypeOf((*MockQuerier)(nil).ListLedgerByEmployeeMonth), ctx, arg)
}

// ListLedgerByTenant mocks base method.
func (m *MockQuerier) ListLedgerByTenant(ctx context.Context, arg repositories.ListLedgerByTenantParams) ([]repositories.Ledger, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLedgerByTenant", ctx, arg)
	ret0, _ := ret[0].([]repositories.Ledger)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListLedgerByTenant indicates an expected call of ListLedgerByTenant.
func (mr *MockQuerierMockRecorder) ListLedgerByTenant(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLedgerByTenant", reflect.TypeOf((*MockQuerier)(nil).ListLedgerByTenant), ctx, arg)
}

// ListPendingSyncEvents mocks base method.
func (m *MockQuerier) ListPendingSyncEvents(ctx context.Context, arg repositories.ListPendingSyncEventsParams) ([]repositories.SyncQueue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPendingSyncEvents", ctx, arg)
	ret0, _ := ret[0].([]repositories.SyncQueue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPendingSyncEvents indicates an expected call of ListPendingSyncEvents.
func (mr *MockQuerierMockRecorder) ListPendingSyncEvents(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPendingSyncEvents", reflect.TypeOf((*MockQuerier)(nil).ListPendingSyncEvents), ctx, arg)
}

// ListShiftsByTenant mocks base method.
func (m *MockQuerier) ListShiftsByTenant(ctx context.Context, arg repositories.ListShiftsByTenantParams) ([]repositories.Shift, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListShiftsByTenant", ctx, arg)
	ret0, _ := ret[0].([]repositories.Shift)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListShiftsByTenant indicates an expected call of ListShiftsByTenant.
func (mr *MockQuerierMockRecorder) ListShiftsByTenant(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListShiftsByTenant", reflect.TypeOf((*MockQuerier)(nil).ListShiftsByTenant), ctx, arg)
}

// LockAttendanceMonth mocks base method.
func (m *MockQuerier) LockAttendanceMonth(ctx context.Context, arg repositories.LockAttendanceMonthParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LockAttendanceMonth", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// LockAttendanceMonth indicates an expected call of LockAttendanceMonth.
func (mr *MockQuerierMockRecorder) LockAttendanceMonth(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LockAttendanceMonth", reflect.TypeOf((*MockQuerier)(nil).LockAttendanceMonth), ctx, arg)
}

// SoftDeleteEmployee mocks base method.
func (m *MockQuerier) SoftDeleteEmployee(ctx context.Context, arg repositories.SoftDeleteEmployeeParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDeleteEmployee", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDeleteEmployee indicates an expected call of SoftDeleteEmployee.
func (mr *MockQuerierMockRecorder) SoftDeleteEmployee(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDeleteEmployee", reflect.TypeOf((*MockQuerier)(nil).SoftDeleteEmployee), ctx, arg)
}

// UpdateAdvanceRequestStatus mocks base method.
func (m *MockQuerier) UpdateAdvanceRequestStatus(ctx context.Context, arg repositories.UpdateAdvanceRequestStatusParams) (repositories.AdvanceRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAdvanceRequestStatus", ctx, arg)
	ret0, _ := ret[0].(repositories.AdvanceRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAdvanceRequestStatus indicates an expected call of UpdateAdvanceRequestStatus.
func (mr *MockQuerierMockRecorder) UpdateAdvanceRequestStatus(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAdvanceRequestStatus", reflect.TypeOf((*MockQuerier)(nil).UpdateAdvanceRequestStatus), ctx, arg)
}

// UpdateAttendance mocks base method.
func (m *MockQuerier) UpdateAttendance(ctx context.Context, arg repositories.UpdateAttendanceParams) (repositories.Attendance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAttendance", ctx, arg)
	ret0, _ := ret[0].(repositories.Attendance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAttendance indicates an expected call of UpdateAttendance.
func (mr *MockQuerierMockRecorder) UpdateAttendance(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAttendance", reflect.TypeOf((*MockQuerier)(nil).UpdateAttendance), ctx, arg)
}

// UpdateEmployee mocks base method.
func (m *MockQuerier) UpdateEmployee(ctx context.Context, arg repositories.UpdateEmployeeParams) (repositories.Employee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEmployee", ctx, arg)
	ret0, _ := ret[0].(repositories.Employee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateEmployee indicates an expected call of UpdateEmployee.
func (mr *MockQuerierMockRecorder) UpdateEmployee(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEmployee", reflect.TypeOf((*MockQuerier)(nil).UpdateEmployee), ctx, arg)
}

// UpdateEmployeeDefaultShift mocks base method.
func (m *MockQuerier) UpdateEmployeeDefaultShift(ctx context.Context, arg repositories.UpdateEmployeeDefaultShiftParams) (repositories.Employee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEmployeeDefaultShift", ctx, arg)
	ret0, _ := ret[0].(repositories.Employee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateEmployeeDefaultShift indicates an expected call of UpdateEmployeeDefaultShift.
func (mr *MockQuerierMockRecorder) UpdateEmployeeDefaultShift(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEmployeeDefaultShift", reflect.TypeOf((*MockQuerier)(nil).UpdateEmployeeDefaultShift), ctx, arg)
}

// UpdateEmployeeManager mocks base method.
func (m *MockQuerier) UpdateEmployeeManager(ctx context.Context, arg repositories.UpdateEmployeeManagerParams) (repositories.Employee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEmployeeManager", ctx, arg)
	ret0, _ := ret[0].(repositories.Employee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateEmployeeManager indicates an expected call of UpdateEmployeeManager.
func (mr *MockQuerierMockRecorder) UpdateEmployeeManager(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEmployeeManager", reflect.TypeOf((*MockQuerier)(nil).UpdateEmployeeManager), ctx, arg)
}

// UpdateEmployeePhotoURL mocks base method.
func (m *MockQuerier) UpdateEmployeePhotoURL(ctx context.Context, arg repositories.UpdateEmployeePhotoURLParams) (repositories.Employee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEmployeePhotoURL", ctx, arg)
	ret0, _ := ret[0].(repositories.Employee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateEmployeePhotoURL indicates an expected call of UpdateEmployeePhotoURL.
func (mr *MockQuerierMockRecorder) UpdateEmployeePhotoURL(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEmployeePhotoURL", reflect.TypeOf((*MockQuerier)(nil).UpdateEmployeePhotoURL), ctx, arg)
}

// UpdateShift mocks base method.
func (m *MockQuerier) UpdateShift(ctx context.Context, arg repositories.UpdateShiftParams) (repositories.Shift, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateShift", ctx, arg)
	ret0, _ := ret[0].(repositories.Shift)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateShift indicates an expected call of UpdateShift.
func (mr *MockQuerierMockRecorder) UpdateShift(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateShift", reflect.TypeOf((*MockQuerier)(nil).UpdateShift), ctx, arg)
}

// UpdateSyncEventStatus mocks base method.
func (m *MockQuerier) UpdateSyncEventStatus(ctx context.Context, arg repositories.UpdateSyncEventStatusParams) (repositories.SyncQueue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSyncEventStatus", ctx, arg)
	ret0, _ := ret[0].(repositories.SyncQueue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSyncEventStatus indicates an expected call of UpdateSyncEventStatus.
func (mr *MockQuerierMockRecorder) UpdateSyncEventStatus(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSyncEventStatus", reflect.TypeOf((*MockQuerier)(nil).UpdateSyncEventStatus), ctx, arg)
}

// UpsertLeavePolicy mocks base method.
func (m *MockQuerier) UpsertLeavePolicy(ctx context.Context, arg repositories.UpsertLeavePolicyParams) (repositories.LeavePolicy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertLeavePolicy", ctx, arg)
	ret0, _ := ret[0].(repositories.LeavePolicy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertLeavePolicy indicates an expected call of UpsertLeavePolicy.
func (mr *MockQuerierMockRecorder) UpsertLeavePolicy(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertLeavePolicy", reflect.TypeOf((*MockQuerier)(nil).UpsertLeavePolicy), ctx, arg)
}

// UpsertTenantConfig mocks base method.
func (m *MockQuerier) UpsertTenantConfig(ctx context.Context, arg repositories.UpsertTenantConfigParams) (repositories.TenantConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertTenantConfig", ctx, arg)
	ret0, _ := ret[0].(repositories.TenantConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertTenantConfig indicates an expected call of UpsertTenantConfig.
func (mr *MockQuerierMockRecorder) UpsertTenantConfig(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertTenantConfig", reflect.TypeOf((*MockQuerier)(nil).UpsertTenantConfig), ctx, arg)
}
